In [205]:
# # 주피터노트북 셀 스타일 조절
# from IPython.core.display import display, HTML
# # display(HTML("<style>.container { font-weight: bold !important; }</style>"))
# display(HTML("<style>.container { width: 100% !important; }</style>"))

# # 경고메시지 숨기기
# import warning
# warnings.filterwarnings(action='ignore')

# Numpy 개요
- Numeric + Python = Numpy   
- 
수학 및 과학 연산을 위한 파이썬 패키   지- 
배열이나 행렬 계산에 용이한 메서드를    제- 공
한글로 넘파이로 주로 통칭, 넘피/늄파이라고 부르기   도-  함
관련 사이트 : http://www.numpy   .- org
일반 List에 비해 빠르고, 메모   리 - 효율적

반복문 없이 데이터 배열에 대한    처- 리를 지원함
선형대수와 관련된 다양한    - 기능을 제공함
Refer   e- nce Site
cs231 : http://cs231n.github.io/python-numpy-tutor   i- al/#numpy
https://docs.scipy.org/doc/numpy-dev/user/quic   k- start.html
데이터사이언스스쿨(파이썬버전) - https://g   oo.gl/3hsjbS

## 설치 및 임포트
넘파이는 외부 라이브러리이므로 설치 필요.(아나콘다는 사전 설치됨)
pip install numpy

In [206]:
import numpy as np
np.__version__

'1.26.4'

## ndim(dimention, rank)
- 몇 차원인지 반환

In [207]:
a = np.array(0)

In [208]:
a, a.ndim, type(a)

(array(0), 0, numpy.ndarray)

In [209]:
a = np.array([2, 4, 6])
a, a.ndim, type(a)

(array([2, 4, 6]), 1, numpy.ndarray)

In [210]:
a = [[1,2,3], [4,5,6]]
a

[[1, 2, 3], [4, 5, 6]]

In [211]:
a = np.array( [[1,2,3], [4,5,6]] )
a, a.ndim, type(a)

(array([[1, 2, 3],
        [4, 5, 6]]),
 2,
 numpy.ndarray)

In [212]:
a = np.array( [[[1,2,3], [4,5,6]], [[1,2,3], [4,5,6]]] )
a, a.ndim, type(a)

(array([[[1, 2, 3],
         [4, 5, 6]],
 
        [[1, 2, 3],
         [4, 5, 6]]]),
 3,
 numpy.ndarray)

## shape
행렬의 차원으로, 몇행 몇열인지 반환

In [213]:
a.shape?

Type:        tuple
String form: (2, 2, 3)
Length:      3
Docstring:  
Built-in immutable sequence.

If no argument is given, the constructor returns an empty tuple.
If iterable is specified the tuple is initialized from iterable's items.

If the argument is a tuple, the return value is the same object.

In [214]:
a = np.array(3)
a, a.shape # 행렬아님

(array(3), ())

In [215]:
a = np.array([ 1, 3, 5, 7, 9 ])
a, a.shape

(array([1, 3, 5, 7, 9]), (5,))

In [216]:
a = np.array( [[1,2,3], [4,5,6]] )
a, a.shape

(array([[1, 2, 3],
        [4, 5, 6]]),
 (2, 3))

In [217]:
a = np.array([[[0, 0, 0, 0], [0, 0, 0, 0], [0, 0, 0, 0]], [[0, 0, 0, 0], [0, 0, 0, 0], [0, 0, 0, 0]]])
a, a.shape # 2개의 3행 4열

(array([[[0, 0, 0, 0],
         [0, 0, 0, 0],
         [0, 0, 0, 0]],
 
        [[0, 0, 0, 0],
         [0, 0, 0, 0],
         [0, 0, 0, 0]]]),
 (2, 3, 4))

## 넘파이 배열
- 리스트를 넘파이 배열로 생성 np.array(리스트)
- 
관련 속성 : ndim 차원 반환 int , size 전체 길이 반환 int, shape 구조 반환 tuple

In [218]:
# 1차원 리스트 객체(이터러블)
myList = [10, 56, 77, 23, 44]
print(myList, type(myList), len(myList))

[10, 56, 77, 23, 44] <class 'list'> 5


In [219]:
myArr = np.array(myList)
print(myArr, type(myArr), len(myArr))
print(f'차원={myArr.ndim}, 구조={myArr.shape}, size={myArr.size}, 길이={len(myArr)}')

[10 56 77 23 44] <class 'numpy.ndarray'> 5
차원=1, 구조=(5,), size=5, 길이=5


In [220]:
myArr

array([10, 56, 77, 23, 44])

In [221]:
# 2차원 리스트 객체(이터러블)
myList2 = [[1,2,3 ],[10,20,30],[100,200,300]]
myList2, len(myList2)

([[1, 2, 3], [10, 20, 30], [100, 200, 300]], 3)

In [222]:
myArr2 = np.array(myList2)
print(myArr2, type(myArr2), len(myArr2))
print(f'차원= {myArr2.ndim}, 구조 = {myArr2.shape}, size = {myArr2.size}, 길이={len(myArr2)}' )

[[  1   2   3]
 [ 10  20  30]
 [100 200 300]] <class 'numpy.ndarray'> 3
차원= 2, 구조 = (3, 3), size = 9, 길이=3


In [223]:
# 2차원 리스트에서 각 행의 수가 다를 경우?
myList21 = [ [1,2,3,4],[10,20,30,40,50],[100,200,]]
print(myList21, type(myList21), len(myList21))

[[1, 2, 3, 4], [10, 20, 30, 40, 50], [100, 200]] <class 'list'> 3


In [224]:
# # 길이가 달라 에러 리턴
# myArr21 = np.array(myList21)
# print(myArr21, type(myArr21), len(myArr21))
# print(f'차원= {myArr21.ndim}, 구조 = {myArr21.shape}, size = {myArr21.size}')

## 넘파이 배열과 리스트와의 차이점

 - 배열간의 연산 가능 "브로드캐스팅", 요소별 연산(element-wise)
 - 
넘파이 메서드 사용 가능 : 평균, 상관계수, 분산, 표준편차 등 - 
리스트는 자료형 혼합 가능, 넘파이배열은 하나의 자료형만 가능

# 리스트의 산술연산자 +, * 
listA = [10, 30, 50]
listB = [1, 2, 3]
print(listA + listB) # 리스트의 + 연산자는 조인역할
print(listA + 2) # 불가

In [225]:
# print(listA * 2) # 해당 리스트의 반복
# print(listA * listB) # 불가

In [226]:
# 넘파이의 산술연산
arrA = np.array([1, 2, 3])
print(arrA + 2)
print(arrA * 2)

[3 4 5]
[2 4 6]


In [227]:
arrB = np.array([4, 5, 6])
print(arrA + arrB)
print(arrA * arrB)
print(arrA / arrB)
print(arrA // arrB) # 몫
print(arrA % arrB) # 나머지

[5 7 9]
[ 4 10 18]
[0.25 0.4  0.5 ]
[0 0 0]
[1 2 3]


## dtype
https://numpy.org/doc/stable/reference/arrays.dtypes.html
데이터 U유형은 각 유니코드 문자를 32비트 정수(예: 4바이트)로 저장합니다. (유니코드 스트링 dtype 인수로 지정할 자료형은 다음 표에 보인것과 같은 “dtype 접두사”로 시작하는 문자열이고 이 글자 뒤에 오는 숫자는 바이트 수 혹은 글자 수를 의미한다.
예를 들어 f8은 8바이트(64비트) 부동소수점 실수를 뜻하고 U4 는 4글자 유니코드 문자열을 뜻한다

In [228]:
# 자료형 테스트
myList_c = ['안녕', 100, 3.14, True, False] # 리스트는 혼합된 형 그대로 유지
print(myList_c)

['안녕', 100, 3.14, True, False]


In [229]:
myArr_c = np.array(myList_c) # 넘파이배열은 '문자열'로 통일 자동형변환
print(myArr_c, type(myArr_c), myArr_c.dtype)

['안녕' '100' '3.14' 'True' 'False'] <class 'numpy.ndarray'> <U32


In [230]:
# 정수와 실수가 혼합된 넘파이 배열
myArr_d = np.array([100, 3.14, 23.5, 0])
print(myArr_d, type(myArr_d), myArr_d.dtype) # 정수와 실수 혼합시, 더 큰 실수형으로 통일 자동형변환

[100.     3.14  23.5    0.  ] <class 'numpy.ndarray'> float64


## Inf와 NaN

넘파이에서는 무한대를 표현하기 위한 np.inf(infinity)와 정의할 수 없는 숫자를 나타내는 np.nan(not a number)을 사용할 수 있다.
다음 예와 같이 1을 0으로 나누려고 하거나 0에 대한 로그 값을 계산하면 무한대인 np.inf이 나온다.
0을 0으로 나누려고 시도하면 np.nan이 나온다.

In [231]:
np.array([0, 1, -1, 0]) / np.array([1, 0, 0, 0])

C:\Users\gkdme\AppData\Local\Temp\ipykernel_22328\2068585620.py:1: RuntimeWarning: divide by zero encountered in divide
  np.array([0, 1, -1, 0]) / np.array([1, 0, 0, 0])
C:\Users\gkdme\AppData\Local\Temp\ipykernel_22328\2068585620.py:1: RuntimeWarning: invalid value encountered in divide
  np.array([0, 1, -1, 0]) / np.array([1, 0, 0, 0])


array([  0.,  inf, -inf,  nan])

In [232]:
np.log(0)

C:\Users\gkdme\AppData\Local\Temp\ipykernel_22328\2933082444.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(0)


-inf

In [233]:
np.exp(-np.inf)

0.0

## 기술통계

In [234]:
x = np.array([18,   5,  10,  23,  19,  -8,  10,   0,   0,   5,   2,  15,   8,
              2,   5,   4,  15,  -1,   4,  -7, -24,   7,   9,  -6,  23, -13])

In [235]:
x.mean()

4.8076923076923075

In [236]:
np.mean(x)  # 평균

4.8076923076923075

In [237]:
np.var(x)  # 분산

115.23224852071006

In [238]:
np.std(x)  # 표준 편차

10.734628476137871

In [239]:
np.max(x), x.max()  # 최댓값

(23, 23)

In [240]:
np.min(x)  # 최소값

-24

In [241]:
np.median(x)  # 중앙값

5.0

## 사분위수

사분위수(quartile)는 데이터를 가장 작은 수부터 가장 큰 수까지 크기가 커지는 순서대로 정렬하였을 때 1/4, 2/4, 3/4 위치에 있는 수를 말한다.
각각 1사분위수, 2사분위수, 3사분위수라고 한다.
1/4의 위치란 전체 데이터의 수가 만약 100개이면 25번째 순서, 즉 하위 25%를 말한다. 따라서 2사분위수는 중앙값과 같다.

때로는 위치를 1/100 단위로 나눈 백분위수(percentile)을 사용하기도 한다. 1사분위수는 25% 백분위수와 같다.

In [242]:
np.percentile(x, 0)  # 최소값

-24.0

In [243]:
np.percentile(x, 25)  # 1사분위 수

0.0

In [244]:
np.percentile(x, 50)  # 2사분위 수

5.0

In [245]:
np.percentile(x, 75)  # 3사분위 수

10.0

In [246]:
np.percentile(x, 100)  # 최댓값

23.0

## 넘파이 함수로 배열 만들기

np.ones(n) , np.ones((x, y))   
np.zeros(n) , np.zeros((x, y))   
np.empty(n) , np.empty((x, y))   
np.aranges(start, end step)   
 
reshape(x, y) # 차원 확대   
flatten(x, y) # 차원 축소   

In [247]:
# 1로 메모리 초기화, 넘파이 함수로 배열을 만들때에는 디폴트가 실수형
print(np.ones(10), np.ones(10).dtype) 

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.] float64


In [248]:
print(np.ones((2,4)), np.ones((2,4)).dtype)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]] float64


In [249]:
np.ones?

Signature: np.ones(shape, dtype=None, order='C', *, like=None)
Docstring:
Return a new array of given shape and type, filled with ones.

Parameters
----------
shape : int or sequence of ints
    Shape of the new array, e.g., ``(2, 3)`` or ``2``.
dtype : data-type, optional
    The desired data-type for the array, e.g., `numpy.int8`.  Default is
    `numpy.float64`.
order : {'C', 'F'}, optional, default: C
    Whether to store multi-dimensional data in row-major
    (C-style) or column-major (Fortran-style) order in
    memory.
like : array_like, optional
    Reference object to allow the creation of arrays which are not
    NumPy arrays. If an array-like passed in as ``like`` supports
    the ``__array_function__`` protocol, the result will be defined
    by it. In this case, it ensures the creation of an array object
    compatible with that passed in via this argument.

    .. versionadded:: 1.20.0

Returns
-------
out : ndarray
    Array of ones with the given shape, dtype, and orde

In [250]:
print(np.ones(10, dtype = int), np.ones(10, dtype = int).dtype)

[1 1 1 1 1 1 1 1 1 1] int32


In [251]:
# 0으로 메모리 초기화
print(np.zeros(10), np.zeros(10).dtype)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.] float64


In [252]:
print(np.zeros((3,3)), np.zeros((3,3)).dtype)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]] float64


In [253]:
np.empty?

Docstring:
empty(shape, dtype=float, order='C', *, like=None)

Return a new array of given shape and type, without initializing entries.

Parameters
----------
shape : int or tuple of int
    Shape of the empty array, e.g., ``(2, 3)`` or ``2``.
dtype : data-type, optional
    Desired output data-type for the array, e.g, `numpy.int8`. Default is
    `numpy.float64`.
order : {'C', 'F'}, optional, default: 'C'
    Whether to store multi-dimensional data in row-major
    (C-style) or column-major (Fortran-style) order in
    memory.
like : array_like, optional
    Reference object to allow the creation of arrays which are not
    NumPy arrays. If an array-like passed in as ``like`` supports
    the ``__array_function__`` protocol, the result will be defined
    by it. In this case, it ensures the creation of an array object
    compatible with that passed in via this argument.

    .. versionadded:: 1.20.0

Returns
-------
out : ndarray
    Array of uninitialized (arbitrary) data of the gi

In [254]:
# 메모리가 비어있음 -> 메모리가 초기화 되지 않는다.
print(np.empty(10), np.empty(10).dtype)
print(np.empty((3,3)), np.empty((3,3)).dtype)
print(np.empty((3,3)))
print(np.empty((3,3), dtype=int))  # 기존 메모리에 있던 값을 출력한다.(정확히 알수 없음)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.] float64
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]] float64
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[  1   2   3]
 [ 10  20  30]
 [100 200 300]]


In [255]:
# 리스트+레인지
print( list(range(1,21)), type(list(range(1,21))) )

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20] <class 'list'>


In [256]:
# 1~20으로 구성된 4행 5열의 넘파이 배열print(np.array(list(range(1,21))), type(list(range(1,21))))
print(np.arange(20), type(np.arange(20)))
print(np.arange(1, 20), type(np.arange(1, 20)))
print(np.arange(1, 20, 2), type(np.arange(1, 20,2)))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19] <class 'numpy.ndarray'>
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19] <class 'numpy.ndarray'>
[ 1  3  5  7  9 11 13 15 17 19] <class 'numpy.ndarray'>


In [257]:
# linspace 명령이나 logspace 명령은 선형 구간 혹은 로그 구간을 지정한 구간의 수만큼 분할한다.
np.linspace(0, 100, 5)  # 시작, 끝(포함), 갯수

array([  0.,  25.,  50.,  75., 100.])

In [258]:
np.linspace?

Signature:      
np.linspace(
    start,
    stop,
    num=50,
    endpoint=True,
    retstep=False,
    dtype=None,
    axis=0,
)
Call signature:  np.linspace(*args, **kwargs)
Type:            _ArrayFunctionDispatcher
String form:     <function linspace at 0x000002B9012D82C0>
File:            c:\users\gkdme\anaconda3\lib\site-packages\numpy\core\function_base.py
Docstring:      
Return evenly spaced numbers over a specified interval.

Returns `num` evenly spaced samples, calculated over the
interval [`start`, `stop`].

The endpoint of the interval can optionally be excluded.

.. versionchanged:: 1.16.0
    Non-scalar `start` and `stop` are now supported.

.. versionchanged:: 1.20.0
    Values are rounded towards ``-inf`` instead of ``0`` when an
    integer ``dtype`` is specified. The old behavior can
    still be obtained with ``np.linspace(start, stop, num).astype(int)``

Parameters
----------
start : array_like
    The starting value of the sequence.
stop : array_like
    The end v

In [259]:
np.logspace(0.1, 1, 10)

array([ 1.25892541,  1.58489319,  1.99526231,  2.51188643,  3.16227766,
        3.98107171,  5.01187234,  6.30957344,  7.94328235, 10.        ])

In [260]:
np.logspace?

Signature:      
np.logspace(
    start,
    stop,
    num=50,
    endpoint=True,
    base=10.0,
    dtype=None,
    axis=0,
)
Call signature:  np.logspace(*args, **kwargs)
Type:            _ArrayFunctionDispatcher
String form:     <function logspace at 0x000002B9012D84A0>
File:            c:\users\gkdme\anaconda3\lib\site-packages\numpy\core\function_base.py
Docstring:      
Return numbers spaced evenly on a log scale.

In linear space, the sequence starts at ``base ** start``
(`base` to the power of `start`) and ends with ``base ** stop``
(see `endpoint` below).

.. versionchanged:: 1.16.0
    Non-scalar `start` and `stop` are now supported.

.. versionchanged:: 1.25.0
    Non-scalar 'base` is now supported

Parameters
----------
start : array_like
    ``base ** start`` is the starting value of the sequence.
stop : array_like
    ``base ** stop`` is the final value of the sequence, unless `endpoint`
    is False.  In that case, ``num + 1`` values are spaced over the
    interval in l

## reshape 구조의 재배열

reshape함수는 np.reshape(변경할 배열, 차원) 또는 배열.reshape(차원)으로 사용 할 수 있으며,
현재의 배열의 차원(1차원,2차원,3차원)을 변경하여 행렬을 반환하거나 하는 경우에 많이 이용되는 함수이다.

In [261]:
# 0~49까지 구성된 넘파이 배열
arr = np.arange(50)
print(arr, len(arr), arr.size)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49] 50 50


In [262]:
arr, arr.ndim, arr.shape

(array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
        17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
        34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49]),
 1,
 (50,))

In [263]:
arr = arr.reshape(10,5)
arr, arr.ndim, arr.shape

(array([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49]]),
 2,
 (10, 5))

In [264]:
arr2 = arr.reshape(5,10)
arr2, arr2.ndim, arr2.shape

(array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]]),
 2,
 (5, 10))

In [265]:
# 2차원 -> 1차원
# 넘파이배열.flatten()
arr3 = arr2.flatten()
arr3, arr3.shape, arr3.ndim

(array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
        17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
        34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49]),
 (50,),
 1)

In [266]:
# 1~100 사이의 짝수로 된 넘파이 배열 생성
np.arange(2,101,2)

array([  2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,  26,
        28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,  52,
        54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,  78,
        80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100])

In [267]:
print(np.arange(2,101,2).reshape(5,10))

[[  2   4   6   8  10  12  14  16  18  20]
 [ 22  24  26  28  30  32  34  36  38  40]
 [ 42  44  46  48  50  52  54  56  58  60]
 [ 62  64  66  68  70  72  74  76  78  80]
 [ 82  84  86  88  90  92  94  96  98 100]]


In [268]:
np.arange(1, 31)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [269]:
# 2차원인데 1개 칼럼의 모형을 만들어보자
# reshape(-1, n) : 2차원 n개의 컬럼으로 구성, -1을 넣으면 자동으로 사이즈를 맞춰준다.
arr4 = np.arange(1, 31).reshape(-1, 1)
arr4, arr4.ndim, arr4.shape

(array([[ 1],
        [ 2],
        [ 3],
        [ 4],
        [ 5],
        [ 6],
        [ 7],
        [ 8],
        [ 9],
        [10],
        [11],
        [12],
        [13],
        [14],
        [15],
        [16],
        [17],
        [18],
        [19],
        [20],
        [21],
        [22],
        [23],
        [24],
        [25],
        [26],
        [27],
        [28],
        [29],
        [30]]),
 2,
 (30, 1))

In [270]:
arr4 = np.arange(1, 31).reshape(1, -1)
arr4, arr4.ndim, arr4.shape

(array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
         17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30]]),
 2,
 (1, 30))

In [271]:
arr4 = np.arange(1, 31).reshape(5, 6)
arr4, arr4.ndim, arr4.shape

(array([[ 1,  2,  3,  4,  5,  6],
        [ 7,  8,  9, 10, 11, 12],
        [13, 14, 15, 16, 17, 18],
        [19, 20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29, 30]]),
 2,
 (5, 6))

In [272]:
arr4 = np.arange(1, 21).reshape(4, 5)
arr4, arr4.ndim, arr4.shape

(array([[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10],
        [11, 12, 13, 14, 15],
        [16, 17, 18, 19, 20]]),
 2,
 (4, 5))

In [273]:
arr4 = np.arange(1, 21).reshape(-1, 5)
arr4, arr4.ndim, arr4.shape

(array([[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10],
        [11, 12, 13, 14, 15],
        [16, 17, 18, 19, 20]]),
 2,
 (4, 5))

In [274]:
a = np.arange(12)
a, a.shape

(array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11]), (12,))

In [275]:
# 원본 값이 바뀜
a.shape = 2, -1
a, a.shape

(array([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11]]),
 (2, 6))

In [276]:
a.shape = 3, -1
a, a.shape

(array([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]),
 (3, 4))

In [277]:
a.shape = -1, 1
a, a.shape

(array([[ 0],
        [ 1],
        [ 2],
        [ 3],
        [ 4],
        [ 5],
        [ 6],
        [ 7],
        [ 8],
        [ 9],
        [10],
        [11]]),
 (12, 1))

In [278]:
# flatten
a.shape = -1
a, a.shape

(array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11]), (12,))

## 넘파이배열의 자료형 형변환

배열명2 = 배열명1.astype(자료형)    
자료형 = np.float64, np.int32

In [279]:
matrix1 = np.arange(1, 10)
matrix1, matrix1.dtype

(array([1, 2, 3, 4, 5, 6, 7, 8, 9]), dtype('int32'))

In [280]:
# 정수형, 3행 3열
matrix = np.arange(1, 10).reshape(3,3)
matrix, matrix.dtype

(array([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]),
 dtype('int32'))

In [281]:
# 실수형, 3행 3열
matrix = np.arange(1, 10, dtype=float).reshape(3,3)
matrix, matrix.dtype

(array([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]]),
 dtype('float64'))

In [282]:
# # 문자열형, 3행 3열 -> 불가
# matrix = np.arange(1, 10, dtype='str').reshape(3,3)
# matrix, matrix.dtype

In [283]:
# 정수형 => 문자열
matrix.astype('<U5')

array([['1.0', '2.0', '3.0'],
       ['4.0', '5.0', '6.0'],
       ['7.0', '8.0', '9.0']], dtype='<U5')

In [284]:
# 논리형으로 구성된 넘파이 배열 생성
matrix2 = np.array([True, False, True, True])
matrix2, matrix2.dtype

(array([ True, False,  True,  True]), dtype('bool'))

In [285]:
# 불린 -> 정수
matrix2.astype(int)

array([1, 0, 1, 1])

In [286]:
# 불린형 -> 문자열
matrix2.astype('<U5')

array(['True', 'False', 'True', 'True'], dtype='<U5')

In [287]:
# 문자열 숫자 => 정수 , 실수
matrix3 = np.array(['3.14', '5.5', '0.78'])
matrix3, matrix3.dtype

(array(['3.14', '5.5', '0.78'], dtype='<U4'), dtype('<U4'))

In [288]:
# print(matrix3.astype(float))

# print(matrix3.astype(int)) # 불가
# print(matrix3.astype(bool)) # 불가

In [289]:
matrix4 = np.array(['3', '5', '7'])
matrix4.astype(int)  # 가능, 값이 유효하기 때문

array([3, 5, 7])

## 넘파이 배열의 인덱싱

넘파이배열[index] 넘파이배열[i, j], 넘파이배열[i][j] : i행 j 열

### 1D array

In [290]:
a = np.array([1, 3, 5, 7, 9])
a, a.ndim, a.shape, a.size

(array([1, 3, 5, 7, 9]), 1, (5,), 5)

In [291]:
a[0]

1

In [292]:
a[4]

9

In [293]:
a[-1]

9

In [294]:
a[-5]

1

In [295]:
a[[0, 2, 4]]

array([1, 5, 9])

In [296]:
# 행렬 구조로 인덱싱도 가능하다
b = np.array( [[1,3], [4,2]] )
b

array([[1, 3],
       [4, 2]])

In [297]:
# 넘파이배열1을 넘파이배열2로 인덱싱하는 경우. 넘파이배열2는 인덱스 번호로 인식
a[b]

array([[3, 7],
       [9, 5]])

In [298]:
a[2] = 0
a

array([1, 3, 0, 7, 9])

In [299]:
a[1] += 2
a

array([1, 5, 0, 7, 9])

In [300]:
a[0] *= 6
a

array([6, 5, 0, 7, 9])

### 2D array

In [301]:
a = np.arange(15).reshape(3, 5)
a, a.ndim, a.shape, a.size

(array([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]]),
 2,
 (3, 5),
 15)

In [302]:
# 2차원 인덱싱할 때, 값을 하나면 넣으면 행인덱싱
a[0]

array([0, 1, 2, 3, 4])

In [303]:
a[1]

array([5, 6, 7, 8, 9])

In [304]:
a[-1]

array([10, 11, 12, 13, 14])

In [305]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [306]:
# 값이 2개 들어가면, 행/열 인덱싱
a[0, 0]

0

In [307]:
a[0, 2]

2

In [308]:
a[2, 0]

10

In [309]:
a[-1, 0]

10

In [310]:
a = np.arange(15).reshape(3, -1)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [311]:
a[1] = [1, 3, 5, 7, 9]
a

array([[ 0,  1,  2,  3,  4],
       [ 1,  3,  5,  7,  9],
       [10, 11, 12, 13, 14]])

In [312]:
a[-1] = 10
a

array([[ 0,  1,  2,  3,  4],
       [ 1,  3,  5,  7,  9],
       [10, 10, 10, 10, 10]])

In [313]:
a[0] += [1, 2, 3, 4, 5]
a

array([[ 1,  3,  5,  7,  9],
       [ 1,  3,  5,  7,  9],
       [10, 10, 10, 10, 10]])

In [314]:
matrix_a = np.arange(10)
matrix_b = np.arange(12).reshape(3,4)

matrix_a, matrix_b

(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]))

In [315]:
# 1차원에서 첫 요소와 마지막 요소
matrix_a[0], matrix_a[-1]

(0, 9)

In [316]:
# 2차원에서 1번째행 1번째열
matrix_b[0, 0]

0

In [317]:
matrix_b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [318]:
# 2차원 마지막행 마지막열 -> 3행 4열
matrix_b[-1,-1]

11

In [319]:
matrix_b[2][3]

11

In [320]:
# matrix_b에서 3번째행 1번째열의값을 100으로 변경해보자
matrix_b[2,0] = 100
matrix_b

array([[  0,   1,   2,   3],
       [  4,   5,   6,   7],
       [100,   9,  10,  11]])

## 넘파이배열 슬라이싱

1차원
넘파이배열[:end]
넘파이배열[start:]
넘파이배열[start:end]
넘파이배열[start:end:step]

2차원

넘파이배열[행, 열] = [start:end:step, start2:end2:step2]

### 1D array

In [321]:
a = np.array([1, 3, 5, 7, 9])
a, a.ndim, a.shape, a.size

(array([1, 3, 5, 7, 9]), 1, (5,), 5)

In [322]:
a[:]

array([1, 3, 5, 7, 9])

In [323]:
 a[1:]

array([3, 5, 7, 9])

In [324]:
a[-1:]

array([9])

In [325]:
a[:3]

array([1, 3, 5])

In [326]:
a[:-1]

array([1, 3, 5, 7])

In [327]:
a[1:4]

array([3, 5, 7])

In [328]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [329]:
a[1::2]

array([1, 3, 5, 7, 9])

In [330]:
a[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

### 2D array

In [331]:
a = np.arange(10, 25).reshape(3, 5)
a, a.ndim, a.shape, a.size

(array([[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24]]),
 2,
 (3, 5),
 15)

In [332]:
a[:]

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [333]:
a[1:]

array([[15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [334]:
a[1:, 2:]

array([[17, 18, 19],
       [22, 23, 24]])

In [335]:
a[-1:]

array([[20, 21, 22, 23, 24]])

In [336]:
a[-3:]

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [337]:
a[:0]

array([], shape=(0, 5), dtype=int32)

In [338]:
a[:, :] # 행의 범위, 열의 범위

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [339]:
a[:, 1:]

array([[11, 12, 13, 14],
       [16, 17, 18, 19],
       [21, 22, 23, 24]])

In [340]:
a[:, -4:]

array([[11, 12, 13, 14],
       [16, 17, 18, 19],
       [21, 22, 23, 24]])

In [341]:
a[:, :-2]

array([[10, 11, 12],
       [15, 16, 17],
       [20, 21, 22]])

In [342]:
a[:, 1:-1]

array([[11, 12, 13],
       [16, 17, 18],
       [21, 22, 23]])

In [343]:
a = np.arange(10, 100).reshape(9, 10)
a

array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [344]:
a[2:5, :]

array([[30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59]])

In [345]:
a[2:5, 2:5]

array([[32, 33, 34],
       [42, 43, 44],
       [52, 53, 54]])

In [346]:
a

array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [347]:
a[::-1, ::-1]

array([[99, 98, 97, 96, 95, 94, 93, 92, 91, 90],
       [89, 88, 87, 86, 85, 84, 83, 82, 81, 80],
       [79, 78, 77, 76, 75, 74, 73, 72, 71, 70],
       [69, 68, 67, 66, 65, 64, 63, 62, 61, 60],
       [59, 58, 57, 56, 55, 54, 53, 52, 51, 50],
       [49, 48, 47, 46, 45, 44, 43, 42, 41, 40],
       [39, 38, 37, 36, 35, 34, 33, 32, 31, 30],
       [29, 28, 27, 26, 25, 24, 23, 22, 21, 20],
       [19, 18, 17, 16, 15, 14, 13, 12, 11, 10]])

In [348]:
matrix_c = np.arange(1, 26).reshape(5,5)
matrix_c, type(matrix_c), matrix_c.ndim

(array([[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10],
        [11, 12, 13, 14, 15],
        [16, 17, 18, 19, 20],
        [21, 22, 23, 24, 25]]),
 numpy.ndarray,
 2)

In [349]:
# 1차원 슬라이싱, 1행만 출력
matrix_c[0, :], matrix_c[0]

(array([1, 2, 3, 4, 5]), array([1, 2, 3, 4, 5]))

In [350]:
# 2차원 슬라이싱, 1번째행 2번째행 출력
matrix_c[0:2, :], matrix_c[0:2]

(array([[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10]]),
 array([[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10]]))

In [351]:
# 1번째열만 출력
matrix_c[:, 0]

array([ 1,  6, 11, 16, 21])

In [352]:
# 3,4 번째열만 출력
matrix_c[:, 2:4]

array([[ 3,  4],
       [ 8,  9],
       [13, 14],
       [18, 19],
       [23, 24]])

In [353]:
# 특정행의 특정열 슬라이싱
matrix_c[0:3, 0:2]

array([[ 1,  2],
       [ 6,  7],
       [11, 12]])

In [354]:
# 홀수번째 행만 출력
matrix_c[::2, ::]

array([[ 1,  2,  3,  4,  5],
       [11, 12, 13, 14, 15],
       [21, 22, 23, 24, 25]])

In [355]:
# 짝수번쨰행 + 홀수번째열
matrix_c[1::2, ::2]

array([[ 6,  8, 10],
       [16, 18, 20]])

In [356]:
# 리버스 인덱싱
print(matrix_c[::-1, ::]) # 행 뒤집기

[[21 22 23 24 25]
 [16 17 18 19 20]
 [11 12 13 14 15]
 [ 6  7  8  9 10]
 [ 1  2  3  4  5]]


In [357]:
print(matrix_c[::, ::-1]) # 열 뒤집기

[[ 5  4  3  2  1]
 [10  9  8  7  6]
 [15 14 13 12 11]
 [20 19 18 17 16]
 [25 24 23 22 21]]


## 전치행렬
넘파이배열.T : 행과 열 구조 변경

In [358]:
# 3행 2열
matrix_d = np.arange(1,7).reshape(3,2)
matrix_d

array([[1, 2],
       [3, 4],
       [5, 6]])

In [359]:
# 2행 3열로 변환
print(matrix_d.T)

[[1 3 5]
 [2 4 6]]


In [360]:
# reshape과 transpose은 값이 다름을 유의 
print(matrix_d.reshape(2,3)) # reshape는 flatten이 선행

[[1 2 3]
 [4 5 6]]


## 난수로 구성된 넘파이 배열
p.random.randint(start, end, n) : 정수 난수   
np.random.randint(start, end, (i, j))

In [362]:
np.random?

Type:        module
String form: <module 'numpy.random' from 'C:\\Users\\gkdme\\anaconda3\\Lib\\site-packages\\numpy\\random\\__init__.py'>
File:        c:\users\gkdme\anaconda3\lib\site-packages\numpy\random\__init__.py
Docstring:  
Random Number Generation

Use ``default_rng()`` to create a `Generator` and call its methods.

=============== =========================================================
Generator
--------------- ---------------------------------------------------------
Generator       Class implementing all of the random number distributions
default_rng     Default constructor for ``Generator``
=============== =========================================================

============================================= ===
BitGenerator Streams that work with Generator
--------------------------------------------- ---
MT19937
PCG64
PCG64DXSM
Philox
SFC64
============================================= ===

============================================= ===
Getting entropy to initial

In [363]:
# 1~10 사이의 숫자중에서 10개 출력
np.random.randint(1, 10, 10)

array([6, 2, 1, 7, 2, 6, 2, 9, 6, 8])

In [364]:
# 2행 5열로 츨력
np.random.randint(1, 10, (2,5))

array([[6, 7, 6, 7, 1],
       [1, 9, 4, 6, 6]])

## 섞기

In [365]:
np.random.shuffle?

Docstring:
shuffle(x)

Modify a sequence in-place by shuffling its contents.

This function only shuffles the array along the first axis of a
multi-dimensional array. The order of sub-arrays is changed but
their contents remains the same.

.. note::
    New code should use the `~numpy.random.Generator.shuffle`
    method of a `~numpy.random.Generator` instance instead;
    please see the :ref:`random-quick-start`.

Parameters
----------
x : ndarray or MutableSequence
    The array, list or mutable sequence to be shuffled.

Returns
-------
None

See Also
--------
random.Generator.shuffle: which should be used for new code.

Examples
--------
>>> arr = np.arange(10)
>>> np.random.shuffle(arr)
>>> arr
[1 7 5 2 9 4 3 6 0 8] # random

Multi-dimensional arrays are only shuffled along the first axis:

>>> arr = np.arange(9).reshape((3, 3))
>>> np.random.shuffle(arr)
>>> arr
array([[3, 4, 5], # random
       [6, 7, 8],
       [0, 1, 2]])
Type:      builtin_function_or_method

In [366]:
# 10개 무작위 값 만들기
matrix_e = np.arange(1,11)
matrix_e

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [367]:
np.random.shuffle(matrix_e)
matrix_e

array([ 5,  9,  2,  6,  1, 10,  4,  8,  7,  3])

### Quiz : 1~45까지 구성된 숫자 중에서 6개를 뽑아서 로또 번호를 생성하라

In [ ]:
# numCnt = 1
# LottoNums = [0,0,0,0,0,0]
# while numCnt < = 6:
#     num = np.random.randint(1, 45, 1)
    
#     if 
    
    

## 실수 난수
np.random.randn(n) np.random.randn(i, j)

In [368]:
np.random.randn?

Docstring:
randn(d0, d1, ..., dn)

Return a sample (or samples) from the "standard normal" distribution.

.. note::
    This is a convenience function for users porting code from Matlab,
    and wraps `standard_normal`. That function takes a
    tuple to specify the size of the output, which is consistent with
    other NumPy functions like `numpy.zeros` and `numpy.ones`.

.. note::
    New code should use the
    `~numpy.random.Generator.standard_normal`
    method of a `~numpy.random.Generator` instance instead;
    please see the :ref:`random-quick-start`.

If positive int_like arguments are provided, `randn` generates an array
of shape ``(d0, d1, ..., dn)``, filled
with random floats sampled from a univariate "normal" (Gaussian)
distribution of mean 0 and variance 1. A single float randomly sampled
from the distribution is returned if no argument is provided.

Parameters
----------
d0, d1, ..., dn : int, optional
    The dimensions of the returned array, must be non-negative.
    I

In [369]:
matrix1 = np.random.randn(10) # 표준정규분포 0 ~ 분산1
matrix1

array([ 1.46615149, -2.05882495,  0.88456624, -1.3707177 ,  1.47978131,
       -0.45827645,  0.5068299 , -1.98287234, -1.31026119, -0.5920943 ])

In [370]:
matrix2 = np.random.randn(4, 4)
matrix2

array([[-0.59117741, -0.7864542 ,  0.21826685, -0.54150882],
       [-0.69605078, -0.38720883,  1.28313877, -1.27313428],
       [ 0.22430789,  0.29342446,  0.9835168 , -2.31957997],
       [-0.0281898 ,  0.5018632 ,  1.64962072,  1.64877091]])

In [371]:
matrix1.max(), matrix1.min()

(1.4797813112451117, -2.0588249528419116)

## 집계함수에서의 
```
2차원에서의 집계합수(sum, mean)
axis = 0, 1
np.sum(넘파이배열, axis=0/1)
np.mean(넘파이배열, axis=0/1)
np.sort(넘파이배열, axis=   

```0/1)

In [372]:
m1 = np.random.randint(1, 50, (5,5))
m1

array([[36, 45, 15, 43, 31],
       [31, 49, 26, 48, 34],
       [34, 40, 23, 38, 35],
       [32, 18, 24,  5, 35],
       [48, 40, 22, 36, 48]])

In [373]:
np.sum(m1, axis=0) # (x)행 합계

array([181, 192, 110, 170, 183])

In [374]:
np.sum(m1, axis=1) # 열(y) 합계

array([170, 188, 170, 114, 194])

In [375]:
# 1번째행의 합계는
m1[0,:]

array([36, 45, 15, 43, 31])

In [376]:
# 1번째행의 합계는
np.sum(m1[0,:], axis=0) # x축(행 방향) 합계

170

In [380]:
m1[:,2]

array([15, 26, 23, 24, 22])

In [379]:
# 3번째행의 합계는
np.sum(m1[:,2], axis=0) # x축(행 방향) 합계

110

## np.sort()

In [381]:
import numpy as np
# 정수 난수로 구성된 4x3
m2 = np.random.randint(1, 50,(4,3))
m2

array([[37, 24,  7],
       [48, 49,  8],
       [ 2, 37, 13],
       [ 9, 10, 48]])

In [382]:
np.sort(m2) # 행안에서 열정렬

array([[ 7, 24, 37],
       [ 8, 48, 49],
       [ 2, 13, 37],
       [ 9, 10, 48]])

In [385]:
np.sort(m2, axis=0) # 행방향 오름차순(요소별로)

array([[ 2, 10,  7],
       [ 9, 24,  8],
       [37, 37, 13],
       [48, 49, 48]])

In [386]:
m2[::-1, ::] # 행전체가 역순으로 바뀌는 것과는 다르다

array([[ 9, 10, 48],
       [ 2, 37, 13],
       [48, 49,  8],
       [37, 24,  7]])

In [387]:
m2

array([[37, 24,  7],
       [48, 49,  8],
       [ 2, 37, 13],
       [ 9, 10, 48]])

In [388]:
np.sort(m2, axis=1) # 행 데이터 오름차순

array([[ 7, 24, 37],
       [ 8, 48, 49],
       [ 2, 13, 37],
       [ 9, 10, 48]])

In [389]:
m2[::-1, ::-1] 

array([[48, 10,  9],
       [13, 37,  2],
       [ 8, 49, 48],
       [ 7, 24, 37]])

## 인덱스 소팅
np.argsort(넘파이배열, axis=0,1)   

정렬값을 인덱스로 반환 (np.sort()를 인덱스로)

In [390]:
x = np.array([9,5,4])
np.argsort(x) # 오름차순 정렬 4 5 9 의 인덱스 값 

array([2, 1, 0], dtype=int64)

In [391]:
x[np.argsort(x)] # 인덱스값으로 실제 값 출력

array([4, 5, 9])

## 넘파이 배열 요소 추가와 삭제
```
삽입
np.insert(배열, 위치인덱스, 값, axis=0/1)
2차원인 경우 axis를 설정하지 않으면 1차원 배열로 변경되어 삽입출력

삭제
np.delete(배열명, 위치인덱스, axis=0/1)
```

In [392]:
m3 = np.arange(1,11)
m3

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [393]:
np.insert(m3, 0, 100)

array([100,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10])

In [394]:
m3[0]

1

In [395]:
m3[-1]

10

In [396]:
np.insert(m3, -1, 500)  # 인덱싱/슬라이싱 end처럼 인식

array([  1,   2,   3,   4,   5,   6,   7,   8,   9, 500,  10])

In [397]:
np.insert(m3, len(m3), 500) 

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10, 500])

In [398]:
m4 = np.arange(1,10).reshape(3,3)
m4

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [399]:
np.insert(m4, 0, 100) # 2차원배열의 경우 axis 미설정시 1차원으로 변경되어 삽입

array([100,   1,   2,   3,   4,   5,   6,   7,   8,   9])

In [400]:
# 1열으로 [100,100,100] 삽입
np.insert(m4, 0, 100, axis=1)

array([[100,   1,   2,   3],
       [100,   4,   5,   6],
       [100,   7,   8,   9]])

In [401]:
m4.shape, m4.shape[1], len(m4)

((3, 3), 3, 3)

In [402]:
# 마지막 컬럼으로 삽입
# 배열명.shape[1] 칼럼 길이
np.insert(m4, m4.shape[1], [100,200,300], axis=1)

array([[  1,   2,   3, 100],
       [  4,   5,   6, 200],
       [  7,   8,   9, 300]])

In [409]:
# 마지막 행에 삽입
np.insert(m4, m4.shape[0], [100,200,300], axis=0)

array([[  1,   2,   3],
       [  4,   5,   6],
       [  7,   8,   9],
       [100, 200, 300]])

In [411]:
m4

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [410]:
m5 = np.insert(m4, m4.shape[0], [100,200,300], axis=0)
m5

array([[  1,   2,   3],
       [  4,   5,   6],
       [  7,   8,   9],
       [100, 200, 300]])

In [412]:
np.delete(m4, 0, axis=0)

array([[4, 5, 6],
       [7, 8, 9]])

## 배열 합치기
```
np.vstack((배열1,배열2....)) : 세로 합치기
np.hstack((배열1,배열2....)) : 가로 합치기
np.concatenate((배열1, 배열2), axis=0/1 ) 2차원만 가능
```

In [413]:
a = np.array([1,2,3])
b = np.array([4,5,6])
np.vstack((a,b))

array([[1, 2, 3],
       [4, 5, 6]])

In [414]:
np.hstack((a,b))

array([1, 2, 3, 4, 5, 6])

In [415]:
c = np.array([[1,2,3]]) # 2차원
c, c.ndim, c.shape

(array([[1, 2, 3]]), 2, (1, 3))

In [416]:
d = np.array([[4,5,6]]) # 2차원
d, d.ndim, d.shape

(array([[4, 5, 6]]), 2, (1, 3))

In [417]:
f = np.concatenate((c,d), axis=1) #
f, f.ndim, f.shape

(array([[1, 2, 3, 4, 5, 6]]), 2, (1, 6))

In [423]:
x = np.array([[1,2,3], [1,2,3]]) # 2차원
z = np.array([[4,5,6],[4,5,6]]) # 2차원
f = np.concatenate((x,z), axis=0) #
f

array([[1, 2, 3],
       [1, 2, 3],
       [4, 5, 6],
       [4, 5, 6]])

## boolean indexing, mask
```
조건절의 결과는 True, False로 반환
True인 결과의 데이터 반환
넘파이배열[조건절] : ==, !=, <=, >=, &, |, ~
```

In [424]:
matrix = np.arange(1, 21)
matrix

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [425]:
matrix > 10

array([False, False, False, False, False, False, False, False, False,
       False,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True])

In [426]:
matrix[matrix > 10]

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [427]:
(matrix > 10).sum()

10

In [428]:
matrix[matrix > 10].sum()

155

### Quiz : 1~100사이 난수 30개를 추출하여 넘파이 배열을 생성하고, 30보다 크거나 70보다 작은 수를 출력하라

In [445]:
m2 = np.random.randint(1,100, (5,6))
m2, m2[(m2 > 30) & (m2 < 70)]

(array([[34, 31, 82, 72, 21, 35],
        [92, 84, 25, 79, 22, 47],
        [17, 49, 47, 94, 82, 43],
        [55,  9, 95, 40, 77, 80],
        [19, 90, 68, 35, 40, 34]]),
 array([34, 31, 35, 47, 49, 47, 43, 55, 40, 68, 35, 40, 34]))

In [492]:
# ~ 은 reverse를 의미
m2 = np.random.randint(1,100, (5,6))
m2[~(m2 > 30) & (m2 < 70)]

array([15,  4, 11, 27, 24,  4])

In [464]:
m2 = np.random.randint(1,100, (5,6))
m2, m2[(m2 > 90) | (m2 < 10)]

(array([[28, 51, 21, 63, 95, 96],
        [30, 39, 92, 30, 33, 99],
        [ 4,  1, 85, 41, 68,  7],
        [86, 33, 95, 48, 65, 27],
        [65, 49, 45, 83, 27, 58]]),
 array([95, 96, 92, 99,  4,  1,  7, 95]))

In [486]:
m2 = np.random.randint(1,100, (5,6))
m2, m2[~((m2 <= 90) & (m2 >= 10))]

(array([[71, 31, 90, 84, 57, 97],
        [36, 50, 61, 91, 63, 25],
        [99, 93, 22,  6, 66, 69],
        [ 7, 55, 98, 64, 81, 42],
        [ 9, 39, 11, 25, 52, 55]]),
 array([97, 91, 99, 93,  6,  7, 98,  9]))

## fancy indexing(filtering)
```
넘파이 배열에 배열로 인덱싱하면 인덱스 번호로 인식한다.

넘파이배열1[넘파이배열2]
넘파이배열2 : 인덱스 역할 (only 정
```수형)

In [493]:
n = np.random.randint(1,100,30)
i = np.array([0, 2, 3, 10, 20])
n, n[i]

(array([22, 25,  1, 80, 12, 92, 96, 58, 28,  5, 37, 93, 54, 27, 27, 83, 28,
        29, 92, 13, 30, 11, 34, 23, 16, 94, 60, 62, 41,  1]),
 array([22,  1, 80, 37, 30]))

## np.where()를 이용한 필터링
```
np.where(조건식) : 조건식 만족하는 인덱스 반환
np.where(조건식, T, F) : 조건식 만족하면 T값, 아니면F값
배열[np.where(조건식)] : 조건식 만족하는 실제 배열값
```

In [494]:
np.where?

Call signature:  np.where(*args, **kwargs)
Type:            _ArrayFunctionDispatcher
String form:     <built-in function where>
Docstring:      
where(condition, [x, y], /)

Return elements chosen from `x` or `y` depending on `condition`.

.. note::
    When only `condition` is provided, this function is a shorthand for
    ``np.asarray(condition).nonzero()``. Using `nonzero` directly should be
    preferred, as it behaves correctly for subclasses. The rest of this
    documentation covers only the case where all three arguments are
    provided.

Parameters
----------
condition : array_like, bool
    Where True, yield `x`, otherwise yield `y`.
x, y : array_like
    Values from which to choose. `x`, `y` and `condition` need to be
    broadcastable to some shape.

Returns
-------
out : ndarray
    An array with elements from `x` where `condition` is True, and elements
    from `y` elsewhere.

See Also
--------
choose
nonzero : The function that is called when x and y are omitted

Notes


In [495]:
a = np.arange(10)
a, np.where(a < 5, a, 10*a)
# a가 5보다 작으면 a를, 아니면 10을 곱하여 출력

(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([ 0,  1,  2,  3,  4, 50, 60, 70, 80, 90]))

In [496]:
b = np.arange(20, 31)
b, np.where(b<25) # 조건을 하나만 주면 인덱스를 반환함

(array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30]),
 (array([0, 1, 2, 3, 4], dtype=int64),))